# -*- coding: utf-8 -*-
"""pr3_Pokormiak.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19DZyCXqJbFwo_WcoyDVRYplKaGyXp5XC

# I. Оператори порівняння та логічні оператори. Умови.

1. (5б) Створіть цілочисленну змінну зі своїм щасливим або улюбленим числом. Напишіть код, який би автоматизовував наступну задачу.

Якщо число парне, помножте його на 2 та виведіть результат на екран.

Але якщо число непарне, помножте його на 3 та додайте 1 і виведіть на екран.
"""

fav_num = 999
if fav_num % 2 == 0:
  fav_num *= 2
  print (fav_num)
else:
  fav_num = fav_num*3
  fav_num += 1
  print (fav_num)

"""2. (9б) Створіть змінну, що посилається на список. Якщо список пустий, додайте будь-який елемент у кінець списку. Якщо ж ні, то нічого не робіть."""

list_ref_var = [1, 9, 0, 8]
if len(list_ref_var) == 0:
  list_ref_var.append(4)
print(list_ref_var)

"""3. (13б) Створіть рядок зі своїм імʼям латинкою. Напишіть код, який би автоматизовував наступну задачу.

Якщо в імені є літера "а"
 або "i", Виведіть на екран повідомлення "A or I is in the name".



Якщо в імені є літери "o" та "n", Виведіть на екран повідомлення "O and N is in the name".

Також якщо в імені немає літери "о", але є "n", Виведіть на екран повідомлення "Only N is in the name".

В решті випадків виведіть на екран повідомлення "There is no N in the name, but there might be O".

Зверніть увагу, що, наприклад, для імені "Antonina" буде виведено два повідомлення.
"""

str_name = "Anastasia"
name_lowercase = str_name.lower()
if 'a' in name_lowercase or 'i' in name_lowercase:
  print ("A or I is in the name")
if 'n' in name_lowercase:
  if 'o' in name_lowercase:
    print ("O and N are in the name")
  else:
    print ("Only N is in the name")
else:
  print ("There is no N in the name, but there might be O")

"""# II. Comprehensions.

4. (5б) Створіть список, використовуючи if (не if-else), range та comprehension.
"""

if_range_comp_list = [i for i in range (15) if i % 3 == 0]
print (if_range_comp_list)

"""5. (9б) Створіть словник, використовуючи dict comprehension, що містить if else. Коли слід використовувати comprehensions, а коли їх слід уникати?"""

var = 150
dictionary = {'number': 'even' if var % 2 == 0 else 'odd'}
print(dictionary)

"""на мою думку, comprehensions добре використовувати для створення лістів або сетів, і якщо їх просто пояснити (наприклад, додати в ліст лише числа що націло діляться на 3 як у завданні 4, проста логіка). не думаю, що comprehensions підійдуть для додавання елементів у вже існуючі об'єкти, оскільки це лише ускладнить логіку. або не варто їх юзати там де багато if'ів бо це суттєво погішує читабельність коду

6. (9б) Створіть список з рядками та запишіть його у змінну. Створіть ще один список на основі попереднього, де кожен рядок буде містити тільки три перших заглавних символи. Наприклад: ['hello', 'i', 'dont', 'care'] -> ['HEL', 'I', 'DON', 'CAR']. Використання comprehensions обовʼязкове.
"""

pink_maggit_list = ["push", "back", "the", "square", "now", "that", "you've", "kneed", "her", "in", "the", "throat", "well", "there", "you", "go"]
pink_maggit_3_up = [word[:3].upper() for word in pink_maggit_list]
print(pink_maggit_3_up)

"""# III. Цикли.

7. (5б) Продемонструйте роботу циклу while. Не можна використовувати True для запуску циклу, щоб уникнути безкінечного циклу!
"""

test = 0
while test < 10:
  print (test)
  test += 1

"""8. (5б) Напишіть програму, яка виведе на екран непарні числа в діапазоні від 0 до 20 включно."""

for i in range (21):
  if i % 2 != 0:
    print (i)

"""9. (13б) Створіть список з елементами булевого типу або None. Використовуючи цикли, отримайте в результаті список з кортежами, де перший елемент кортежу - індекс(ціле число), а другий елемент - відповідне значення з першого списку.

Наприклад, [True, True, None, False] -> [(0, True), (1, True), (2, None), (3, False)]
"""

bool_none_list = [False, None, True, None, False]
length = len(bool_none_list)
tuple_list = []
for i in range (length):
  ind_val_tuple = (i, bool_none_list[i])
  tuple_list.append(ind_val_tuple)
print (tuple_list)

"""10. (9б) Створіть словник, де ключі - назви книжок, а значення - їхня кількість у наявності в Вашій міні-бібліотеці. Бібліотека має містити щонайменше 6 книжок (6 пар значень у словнику) і щонайбільше 10 (пар значень). Використовуючи цикли, оновіть словник (не створюйте новий) так, щоби кількість книг у наявності збільшилося на 5 кожної книги. Наприклад,
{'It': 3, 'Fault stars': 10, 'Bible': 17, 'Psychological romance': 4, 'Harry Potter': 13} -> {'It': 8, 'Fault stars': 15, 'Bible': 22, 'Psychological romance': 9, 'Harry Potter': 18}
"""

library = {"The Cathcher in the Rye": 4, "1984": 9, "Fight Club": 5, "Good Omens": 2, "American Psycho": 1, "All Quiet on the Western Front": 3, "Animal Farm": 8, "Venus in Furs": 6}
for book in library.keys():
  library[book] += 5
print (library)

"""11. (5б) Визначте цілочислену змінну n, що належить проміжку від 4 до 10 включно. Використовуючи цикли, виведіть в консоль наступний патерн.

#
##
###
####

... #*n

"""

n = 9
for i in range (1, n+1):
  print ("#" * i)

"""12. (13б) Гра "Нумо вгадай".
Розробіть просту гру, де користувач має вгадати випадкове число від 1 до 100. Для генерації випадкового числа використовуйте функцію random.randint(a, b) (тут a та b включно). Для отримання числа з консолі використовуйте функцію input(), результат якої обовʼязково явно приведіть до типу int.

Підказка: використовуйте цикл while та умови if-else, щоб повідомити користувачу піказки (напр. "Більше", "Менше") поки користувач не вгадає. По завершенню виведіть кількість спроб, які знадобилися для вгадування.
"""

import random
secret_number = random.randint (1, 100)
unguessed = True
attempts = 0
while (unguessed):
  print ("введіть число:")
  user_input = input()
  if user_input.isdigit():
    guess = int(user_input)
    if guess > secret_number:
      print ("таємне число менше ніж те що ви ввели")
      attempts += 1
    elif guess < secret_number:
      print ("таємне число більше ніж те що ви ввели")
      attempts += 1
    else:
      print ("ви вгадали! таємне число = ", secret_number)
      attempts += 1
      print ("кількість спроб, що вам знадобилась:", attempts)
      unguessed = False
  else:
    print ("ви ввели не число, спробуйте ще раз")

"""# Вітаю! Ви велика(ий) молодець, що впоралась(вся). Похваліть себе та побалуйте чимось приємним. Я Вами пишаюся."""